# Generated by Django 5.2.4 on 2025-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_lessonreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonreview',
            name='student',
        ),
        migrations.AlterField(
            model_name='lessonreview',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
