# Generated by Django 5.2.4 on 2025-08-23 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_lessonreview_comment_lessonreview_review_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonreview',
            old_name='lesson',
            new_name='booking',
        ),
        migrations.AlterField(
            model_name='lessonreview',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_left', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonreview',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
