# Generated by Django 5.2.4 on 2025-08-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_lesson_lessonreview_booking_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonReview',
        ),
    ]
